M48
; DRILL file {KiCad 7.0.6-0} date 2023 December 23, Saturday 18:43:18
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-23T18:43:18-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6-0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X3.4545Y-2.5244
X3.6455Y-2.5244
T2
X3.4427Y-2.4051
X3.6573Y-2.4051
T0
M30
